import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import sharp from 'sharp';
import {db,create,update,list} from '../src/lib/store.ts';
import {servePlacement,recordDelivery} from '../src/lib/delivery.ts';
import {signDelivery} from '../src/lib/delivery-token.ts';
import {createSession,isAdmin,revokeSession,allowLogin,cookieName} from '../src/lib/auth.ts';
import {saveAsset,readAsset} from '../src/lib/assets.ts';
const dir=mkdtempSync(join(tmpdir(),'one-functional-'));
process.env.DB_PROVIDER=process.env.TEST_DB_PROVIDER||'sqlite';
if(process.env.DB_PROVIDER==='sqlite')process.env.DATABASE_PATH=join(dir,'test.sqlite');
else if(!/^one_adserver_test_/.test(process.env.DB_NAME||''))throw new Error('Use an isolated test DB');
process.env.UPLOAD_DIR=join(dir,'uploads');
process.env.ADMIN_PASSWORD='isolated-test-password';
process.env.DELIVERY_SECRET='isolated-test-delivery-secret';
after(async()=>db().close());

test('assignment isolation, concurrent caps, replay protection, expiry, pacing and no fill',async()=>{
 await db().migrate();
 const a=await create('advertisers',{name:'Functional test'});
 const p=await create('properties',{name:'Site'});
 const x=await create('placements',{name:'Assigned',property_id:p.id,width:300,height:250});
 const y=await create('placements',{name:'Other',property_id:p.id,width:300,height:250});
 const c=await create('campaigns',{name:'Capped',advertiser_id:a.id,daily_cap:3,placement_ids:[x.id]});
 await create('creatives',{name:'Image',campaign_id:c.id,width:300,height:250,image_url:'https://example.com/a.png',target_url:'https://example.com/'});
 const now=new Date('2026-06-01T12:00:00.000Z');
 assert.equal(await servePlacement(y.id,now),null);
 assert.equal(await servePlacement('missing',now),undefined);
 const ads=(await Promise.all(Array.from({length:20},()=>servePlacement(x.id,now)))).filter(Boolean);
 assert.equal(ads.length,3);
 const ad=ads[0],token=signDelivery(ad.requestId);
 assert.equal(await recordDelivery(ad.requestId,'bad','impression',now),null);
 await Promise.all(Array.from({length:8},()=>recordDelivery(ad.requestId,token,'impression',now)));
 await Promise.all(Array.from({length:8},()=>recordDelivery(ad.requestId,token,'click',now)));
 assert.equal((await db().prepare("SELECT COUNT(*) AS n FROM events WHERE campaign_id=? AND kind='impression'").get(c.id)).n,1);
 assert.equal((await db().prepare("SELECT COUNT(*) AS n FROM events WHERE campaign_id=? AND kind='click'").get(c.id)).n,1);
 const later=new Date(now.getTime()+300001);
 assert.equal(await recordDelivery(ads[1].requestId,signDelivery(ads[1].requestId),'impression',later),null);
 const replacement=(await Promise.all(Array.from({length:10},()=>servePlacement(x.id,later)))).filter(Boolean);
 assert.equal(replacement.length,2);
 await update('campaigns',c.id,{pacing:'even',daily_cap:4});
 const tomorrow=new Date('2026-06-02T12:00:00.000Z');
 assert.equal((await Promise.all(Array.from({length:10},()=>servePlacement(x.id,tomorrow)))).filter(Boolean).length,2);
 await update('campaigns',c.id,{placement_ids:[],name:'Edited'});
 assert.equal(await servePlacement(x.id,tomorrow),null);
 assert.deepEqual((await list('campaigns')).find(r=>r.id===c.id).placement_ids,[]);
 await assert.rejects(update('campaigns',c.id,{placement_ids:['missing']}));
 await assert.rejects(update('campaigns',c.id,{start_at:'2026-02-31'}));
 assert.ok((await db().prepare("SELECT COUNT(*) AS n FROM delivery_requests WHERE outcome='empty' AND placement_id=?").get(x.id)).n>0);
});
test('sessions expire, revoke individually/all, reject cross-origin writes and throttle attempts',async()=>{
 const now=new Date(),token=await createSession(now);
 const req=new Request('http://localhost/api/admin/campaigns',{headers:{cookie:`${cookieName}=${token}`}});
 assert.equal(await isAdmin(req,now),true);
 assert.equal(await isAdmin(req,new Date(now.getTime()+8*3600000)),false);
 assert.equal(await isAdmin(new Request(req,{method:'POST',headers:{cookie:`${cookieName}=${token}`,origin:'https://evil.example'}})),false);
 await revokeSession(req);assert.equal(await isAdmin(req),false);
 const other=await createSession();await revokeSession(req,true);
 assert.equal(await isAdmin(new Request(req,{headers:{cookie:`${cookieName}=${other}`}})),false);
 await db().prepare('DELETE FROM login_attempts').run();
 const attempts=await Promise.all(Array.from({length:15},()=>allowLogin(req,now)));
 assert.equal(attempts.filter(Boolean).length,10);
 assert.equal(await allowLogin(req,new Date(now.getTime()+900001)),true);
});
test('uploads decode, normalize, persist and reject unsupported or oversized files',async()=>{
 const png=await sharp({create:{width:300,height:250,channels:3,background:'#7755ff'}}).png().toBuffer();
 const asset=await saveAsset(new File([png],'banner.png',{type:'image/png'}));
 assert.equal(asset.width,300);assert.equal(asset.height,250);
 assert.ok(await readAsset(asset.id));
 await assert.rejects(saveAsset(new File(['<svg/>'],'bad.svg',{type:'image/svg+xml'})));
 await assert.rejects(saveAsset(new File([new Uint8Array(6*1024*1024)],'big.png')));
 assert.equal(await readAsset('../bad'),null);
});
