import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
test('publisher tag waits for image load and sends only one impression',async()=>{
 const nodes=[],pixels=[],slot={dataset:{onePlacement:'placement'},appendChild(){}};
 const ad={name:'Banner',imageUrl:'https://ads.example/image',clickUrl:'https://ads.example/click',impressionUrl:'https://ads.example/impression',width:300,height:250};
 const context={URL,fetch:async()=>({json:async()=>({ad})}),Image:function(){pixels.push(this)},window:{matchMedia:()=>({matches:false,addEventListener(){}})},document:{currentScript:{src:'https://ads.example/ad.js'},querySelectorAll:()=>[slot],createElement:(tag)=>{const element={tag,style:{},appendChild(){}};nodes.push(element);return element;}}};
 vm.runInNewContext(readFileSync(new URL('../public/ad.js',import.meta.url),'utf8'),context);
 await new Promise(resolve=>setImmediate(resolve));
 assert.equal(pixels.length,0);
 const image=nodes.find(node=>node.tag==='img');assert.equal(image.src,ad.imageUrl);
 image.onload();image.onload();assert.equal(pixels.length,1);assert.equal(pixels[0].src,ad.impressionUrl);
});
test('device-specific tags do not request an ad on other devices and load after breakpoint change',async()=>{
 const listeners=[],requests=[],nodes=[],pixels=[];
 let width=1400;
 const slot={dataset:{onePlacement:'mobile-placement',oneDevice:'mobile'},appendChild(){}};
 const ad={name:'Mobile ad',imageUrl:'https://ads.example/image',clickUrl:'https://ads.example/click',impressionUrl:'https://ads.example/impression',width:300,height:250};
 const context={URL,fetch:async url=>{requests.push(url);return {json:async()=>({ad})}},Image:function(){pixels.push(this)},window:{matchMedia:query=>({get matches(){return query.includes('max-width: 767px')?width<=767:query.includes('min-width: 768px')?width>=768&&width<=1199:width>=1200},addEventListener(_event,listener){listeners.push(listener)}})},document:{currentScript:{src:'https://ads.example/ad.js?v=2'},querySelectorAll:()=>[slot],createElement:tag=>{const element={tag,style:{},appendChild(){}};nodes.push(element);return element;}}};
 const source=readFileSync(new URL('../public/ad.js',import.meta.url),'utf8');
 vm.runInNewContext(source,context);
 assert.equal(slot.hidden,true);
 assert.equal(requests.length,0);
 width=390;listeners.forEach(listener=>listener());
 await new Promise(resolve=>setImmediate(resolve));
 assert.equal(slot.hidden,false);
 assert.equal(requests.length,1);
 const image=nodes.find(node=>node.tag==='img');
 image.onload();assert.equal(pixels.length,1);
 width=1400;listeners.forEach(listener=>listener());
 assert.equal(slot.hidden,true);
 assert.equal(requests.length,1);
 vm.runInNewContext(source,context);
 assert.equal(requests.length,1);
});
test('all, tablet and desktop tags select the expected viewport without duplicate requests',async()=>{
 const listeners=[],requests=[];
 let width=900;
 const slots=['all','mobile','tablet','desktop'].map(device=>({dataset:{onePlacement:device,oneDevice:device},appendChild(){}}));
 const context={URL,fetch:async url=>{requests.push(url);return {json:async()=>({ad:null})}},Image:function(){},window:{matchMedia:query=>({get matches(){return query.includes('max-width: 767px')?width<=767:query.includes('min-width: 768px')?width>=768&&width<=1199:width>=1200},addEventListener(_event,listener){listeners.push(listener)}})},document:{currentScript:{src:'https://ads.example/ad.js?v=2'},querySelectorAll:()=>slots,createElement:()=>({style:{},appendChild(){}})}};
 vm.runInNewContext(readFileSync(new URL('../public/ad.js',import.meta.url),'utf8'),context);
 assert.deepEqual(requests.map(url=>new URL(url).searchParams.get('placement')),['all','tablet']);
 width=1300;listeners.forEach(listener=>listener());
 assert.equal(slots[2].hidden,true);
 assert.deepEqual(requests.map(url=>new URL(url).searchParams.get('placement')),['all','tablet','desktop']);
 width=390;listeners.forEach(listener=>listener());
 assert.deepEqual(requests.map(url=>new URL(url).searchParams.get('placement')),['all','tablet','desktop','mobile']);
});
