"use client";
import { useEffect, useState } from "react";
import { Box, Card, CardContent, Chip, LinearProgress, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from "@mui/material";
type Metrics={noFill:number;totals:Record<string,number>;daily:{day:string;kind:string;value:number}[];campaigns:{id:string;name:string;status:string;advertiser:string;impressions:number;clicks:number}[]};
export default function Reports(){
  const [data,setData]=useState<Metrics|null>(null);
  useEffect(()=>{fetch("/api/admin/metrics").then(r=>r.json()).then(setData)},[]);
  const days=Object.values((data?.daily||[]).reduce<Record<string,{day:string;request:number;impression:number;click:number}>>((acc,row)=>{acc[row.day]??={day:row.day,request:0,impression:0,click:0};if(row.kind in acc[row.day])acc[row.day][row.kind as "request"|"impression"|"click"]=row.value;return acc},{})).reverse();
  return <Box sx={{py:3}}><Typography variant="h4" fontWeight={800}>Reports</Typography><Typography color="text.secondary" mt={.5} mb={3}>Delivery results recorded by the ad server.</Typography>{!data&&<LinearProgress/>}
  {data&&<Typography mb={3}>No-fill requests: {data.noFill || 0} · Fill rate: {data.totals?.request?((data.totals.request-(data.noFill||0))/data.totals.request*100).toFixed(1):'0.0'}%</Typography>}
  <Stack spacing={3}><Card elevation={0} sx={{border:"1px solid",borderColor:"divider",borderRadius:3}}><CardContent><Typography variant="h6" fontWeight={800} mb={2}>Campaigns</Typography><TableContainer><Table><TableHead><TableRow><TableCell>Campaign</TableCell><TableCell>Advertiser</TableCell><TableCell>Status</TableCell><TableCell align="right">Impressions</TableCell><TableCell align="right">Clicks</TableCell><TableCell align="right">CTR</TableCell></TableRow></TableHead><TableBody>{data?.campaigns.length?data.campaigns.map(row=><TableRow key={row.id}><TableCell sx={{fontWeight:700}}>{row.name}</TableCell><TableCell>{row.advertiser}</TableCell><TableCell><Chip size="small" label={row.status} color={row.status==="active"?"success":"default"}/></TableCell><TableCell align="right">{row.impressions.toLocaleString()}</TableCell><TableCell align="right">{row.clicks.toLocaleString()}</TableCell><TableCell align="right">{row.impressions?(row.clicks/row.impressions*100).toFixed(2):"0.00"}%</TableCell></TableRow>):<TableRow><TableCell colSpan={6} align="center" sx={{py:5}}>No campaign activity yet.</TableCell></TableRow>}</TableBody></Table></TableContainer></CardContent></Card>
  <Card elevation={0} sx={{border:"1px solid",borderColor:"divider",borderRadius:3}}><CardContent><Typography variant="h6" fontWeight={800} mb={2}>Daily activity</Typography><TableContainer><Table><TableHead><TableRow><TableCell>Date</TableCell><TableCell align="right">Requests</TableCell><TableCell align="right">Impressions</TableCell><TableCell align="right">Clicks</TableCell></TableRow></TableHead><TableBody>{days.length?days.map(row=><TableRow key={row.day}><TableCell>{row.day}</TableCell><TableCell align="right">{row.request}</TableCell><TableCell align="right">{row.impression}</TableCell><TableCell align="right">{row.click}</TableCell></TableRow>):<TableRow><TableCell colSpan={4} align="center" sx={{py:5}}>No delivery events yet.</TableCell></TableRow>}</TableBody></Table></TableContainer></CardContent></Card></Stack></Box>;
}
